### PR TITLE
Fix for #94

### PR DESCRIPTION
**Pull request by jreading**
Package is pointing to git repo and not package version.

### CODE REVIEW

**Comment by marrs** [comment]
Thanks for spotting this, but do you realise that the repo used is a fork of the original project? It contains a fix for ~~IE~~ Windows users. I don't expect to modify the repo again so I will leave it for now. In time, I will move back to the original project but I need to regression test it first.

**Comment by jreading** [comment]
Why not publish a forked version to NPM? Seems like a bummer to break CI servers all over than worry about how an NPM affects IE.

**Comment by marrs** [comment]
Sorry, by IE I meant Windows. How is your CI server complaining?  Will it stop complaining if I specify the commit hash?

**Comment by jreading** [comment]
It's only complaining because git is not installed. 

This may be the only production npm I've seen where git is a hard dep, so I'd imagine this might cause some headaches. I know it seems unlikely that anyone using node/npm would not have git, but you'd be surprised. Getting node installed can be enough of a battle for some. 

For me, it's not the end of the world (I've separated out this package as a devDep in our package.json), but I would consider publishing your forked version or pressuring the maintainers of the other to merge your fix.

Regardless, thanks for the software!

**Comment by marrs** [comment]
Oh, I see; I thought npm used git internally.  Ok, I need to publish my fork ASAP then, or test the latest version of node-findit and see if the bug is fixed (which it may well be).  I'll get onto this tomorrow.  Thanks for bringing this to my attention.

**Comment by jreading** [comment]
I think the NPM repo uses git internally regardless of whether the package is published as https:// or git://, but manually setting the package supersedes that.

**Comment by marrs** [comment]
I added you patch manually to the latest release because I had to modify Styledocco to make it work. Thanks again.

**Pull request closed without merging**
