### PR TITLE
Pass through argument for precompilers

### PR DESCRIPTION
**Pull request by ddlsmurf**
Hi,
  this adds a little argument I use to add included paths needed by lessc.
thanks

### CODE REVIEW

**Comment by jacobrask** [comment]
Great idea, this is something a lot of people will probably need. 

I have to test this with all preprocessors and also think a bit about the syntax, it feels slightly weird passing parameters in a string, but that might be the only way..

**Comment by ddlsmurf** [comment]
2c: After integrating it in my project, I think that I will have styledocco work on the generated CSS instead of the less source anyway: I find myself having comments I don't want in the documentation, and having to repeat my makefile variables into  `--pass` arguments... As you say, feels weird... Great work though, definitely hits the spot

**Comment by jacobrask** [comment]
I had comments like that as well, but you can add a space before any comment and they will not show up in StyleDocco. It was the easiest "syntax" I could come up with for that, and it also means that comments regarding specific properties, which are usually indented with the property or placed after the property, will automatically be hidden.

**Comment by jacobrask** [comment]
Released 0.2.4 with this change, thanks again!

**Pull request closed without merging**
